//! Embed drop-in plugin JSON and config overlays at compile time.
//!
//! Operators add files under `plugins/` (and optional `config/overlays/*.json`).
//! This script re-runs when those directories change and writes
//! `$OUT_DIR/plugin_catalog.rs` for `src/plugins/catalog.rs`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    println!("cargo:rerun-if-changed=plugins");
    println!("cargo:rerun-if-changed=config/overlays");
    println!("cargo:rerun-if-changed=build.rs");

    watch_json(&manifest.join("plugins/themes"));
    watch_json(&manifest.join("plugins/layouts"));
    watch_json(&manifest.join("plugins/providers"));
    watch_json(&manifest.join("plugins/features"));
    watch_json(&manifest.join("config/overlays"));
    watch_dir(&manifest.join("plugins/logos"));

    let mut out = String::new();
    out.push_str("// Generated by build.rs — do not edit.\n");
    emit_include_table(
        &mut out,
        "BUNDLED_THEMES",
        &json_files(&manifest.join("plugins/themes")),
        "plugins/themes",
    );
    emit_include_table(
        &mut out,
        "BUNDLED_LAYOUTS",
        &json_files(&manifest.join("plugins/layouts")),
        "plugins/layouts",
    );
    emit_include_table(
        &mut out,
        "BUNDLED_PROVIDERS",
        &json_files(&manifest.join("plugins/providers")),
        "plugins/providers",
    );
    emit_include_table(
        &mut out,
        "BUNDLED_FEATURES",
        &json_files(&manifest.join("plugins/features")),
        "plugins/features",
    );
    emit_overlay_list(&mut out, &json_files(&manifest.join("config/overlays")));
    let logos = copy_plugin_logos(&manifest);
    emit_logo_list(&mut out, &logos);

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("plugin_catalog.rs");
    fs::write(dest, out).expect("write plugin_catalog.rs");
}

fn watch_json(dir: &Path) {
    if dir.is_dir() {
        for path in json_files(dir) {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn watch_dir(dir: &Path) {
    if dir.is_dir() {
        println!("cargo:rerun-if-changed={}", dir.display());
        if let Ok(rd) = fs::read_dir(dir) {
            for e in rd.flatten() {
                println!("cargo:rerun-if-changed={}", e.path().display());
            }
        }
    }
}

fn json_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let Ok(rd) = fs::read_dir(dir) else {
        return files;
    };
    for e in rd.flatten() {
        let path = e.path();
        if path.extension().and_then(|s| s.to_str()) == Some("json") {
            validate_json(&path);
            files.push(path);
        }
    }
    files.sort();
    files
}

fn validate_json(path: &Path) {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let value: serde_json::Value = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", path.display()));
    if let Some(id) = value.get("id").and_then(|v| v.as_str()) {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        if !id.eq_ignore_ascii_case(stem) && stem != id {
            println!(
                "cargo:warning={} id `{id}` does not match file stem `{stem}`",
                path.display()
            );
        }
    }
}

fn emit_include_table(out: &mut String, const_name: &str, files: &[PathBuf], rel_dir: &str) {
    out.push_str(&format!("pub const {const_name}: &[(&str, &str)] = &[\n"));
    for path in files {
        let stem = path
            .file_name()
            .and_then(|s| s.to_str())
            .expect("utf-8 plugin filename");
        out.push_str(&format!(
            "    (\"{id}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel_dir}/{stem}\"))),\n",
            id = path.file_stem().and_then(|s| s.to_str()).unwrap_or("item"),
        ));
    }
    out.push_str("];\n\n");
}

fn emit_overlay_list(out: &mut String, files: &[PathBuf]) {
    out.push_str("pub const CONFIG_OVERLAYS: &[&str] = &[\n");
    for path in files {
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .expect("utf-8 overlay filename");
        out.push_str(&format!(
            "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/config/overlays/{name}\")),\n"
        ));
    }
    out.push_str("];\n\n");
}

fn skip_logo_name(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    lower == "readme.md" || lower == ".gitkeep" || lower == ".keep" || lower.starts_with('.')
}

fn copy_plugin_logos(manifest: &Path) -> Vec<String> {
    let src = manifest.join("plugins/logos");
    let dst = manifest.join("public/plugins/logos");
    let _ = fs::create_dir_all(&dst);
    let mut public_paths = Vec::new();
    let Ok(rd) = fs::read_dir(&src) else {
        return public_paths;
    };
    for e in rd.flatten() {
        let path = e.path();
        if !path.is_file() {
            continue;
        }
        let name = match path.file_name().and_then(|s| s.to_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };
        if skip_logo_name(&name) {
            continue;
        }
        let dest = dst.join(&name);
        fs::copy(&path, &dest).unwrap_or_else(|err| {
            panic!("copy logo {} -> {}: {err}", path.display(), dest.display());
        });
        public_paths.push(format!("/plugins/logos/{name}"));
    }
    public_paths.sort();
    public_paths
}

fn emit_logo_list(out: &mut String, paths: &[String]) {
    out.push_str("pub const BUNDLED_LOGOS: &[&str] = &[\n");
    for p in paths {
        out.push_str(&format!("    \"{p}\",\n"));
    }
    out.push_str("];\n");
}
